apiVersion: v1
kind: Service
metadata:
  name: router-reverse-proxy-nodeport
spec:
  type: NodePort
  selector:
    app: router-reverse-proxy
  ports:
  - name: http
    port: 2081
    targetPort: 2081
    nodePort: 32081
  # - name: https
  #   port: 443
  #   targetPort: 443
  #   nodePort: 30443
