apiVersion: v1
kind: Service
metadata:
  name: router-reverse-proxy-public
spec:
  type: ClusterIP
  selector:
    app: router-reverse-proxy
  ports:
  # - name: http
  #   port: 2081
  #   targetPort: 2081
  - name: http
    port: 10000
    targetPort: 10000

  # - name: https
  #   port: 443
  #   targetPort: 443
